-- CUSTOMERS
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, BIRTH_DATE, GENDER, PHONE, EMAIL, ADDRESS, OCCUPATION, ANNUAL_INCOME, REG_DATE)
VALUES (1, '한라봉', TO_DATE('1985-04-15','YYYY-MM-DD'), 'M', '010-1111-2222', 'hallabong@test.com', '서울시 강남구', '회사원', 60000000, SYSDATE);

INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, BIRTH_DATE, GENDER, PHONE, EMAIL, ADDRESS, OCCUPATION, ANNUAL_INCOME, REG_DATE)
VALUES (2, '진지향', TO_DATE('1990-08-20','YYYY-MM-DD'), 'M', '010-2222-3333', 'jinhyang@test.com', '경기도 분당구', '자영업', 45000000, SYSDATE);

INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, BIRTH_DATE, GENDER, PHONE, EMAIL, ADDRESS, OCCUPATION, ANNUAL_INCOME, REG_DATE)
VALUES (3, '천혜향', TO_DATE('1988-11-05','YYYY-MM-DD'), 'F', '010-3333-4444', 'cheonhye@test.com', '서울시 서초구', '교사', 55000000, SYSDATE);

INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, BIRTH_DATE, GENDER, PHONE, EMAIL, ADDRESS, OCCUPATION, ANNUAL_INCOME, REG_DATE)
VALUES (4, '윈터프린스', TO_DATE('1995-02-18','YYYY-MM-DD'), 'F', '010-4444-5555', 'winter@test.com', '인천시 연수구', '프리랜서', 35000000, SYSDATE);

INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, BIRTH_DATE, GENDER, PHONE, EMAIL, ADDRESS, OCCUPATION, ANNUAL_INCOME, REG_DATE)
VALUES (5, '레드향', TO_DATE('1975-09-30','YYYY-MM-DD'), 'M', '010-5555-6666', 'redhyang@test.com', '부산시 해운대구', '임원', 120000000, SYSDATE);

INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, BIRTH_DATE, GENDER, PHONE, EMAIL, ADDRESS, OCCUPATION, ANNUAL_INCOME, REG_DATE)
VALUES (6, '설국향', TO_DATE('2000-01-10','YYYY-MM-DD'), 'F', '010-6666-7777', 'seolguk@test.com', '서울시 마포구', '학생', 15000000, SYSDATE);

-- 미계약 고객 (OUTER JOIN 실습용)
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, BIRTH_DATE, GENDER, PHONE, EMAIL, ADDRESS, OCCUPATION, ANNUAL_INCOME, REG_DATE)
VALUES (7, '타이벡', TO_DATE('1992-07-07','YYYY-MM-DD'), 'M', '010-7777-8888', 'tyvek@test.com', '제주시 노형동', '개발자', 70000000, SYSDATE);

INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, BIRTH_DATE, GENDER, PHONE, EMAIL, ADDRESS, OCCUPATION, ANNUAL_INCOME, REG_DATE)
VALUES (8, '감홍', TO_DATE('1983-12-25','YYYY-MM-DD'), 'F', '010-8888-9999', 'gamhong@test.com', '대전시 유성구', '연구원', 85000000, SYSDATE);


-- 2. CONTRACTS
INSERT INTO CONTRACTS (CONTRACT_ID, CUSTOMER_ID, PRODUCT_ID, CONTRACT_DATE, EXPIRY_DATE, MONTHLY_PREMIUM, STATUS, AGENT_NAME)
VALUES (1, 1, 1, TO_DATE('2023-01-15','YYYY-MM-DD'), TO_DATE('2033-01-15','YYYY-MM-DD'), 15000, '유지', '김설계');

INSERT INTO CONTRACTS (CONTRACT_ID, CUSTOMER_ID, PRODUCT_ID, CONTRACT_DATE, EXPIRY_DATE, MONTHLY_PREMIUM, STATUS, AGENT_NAME)
VALUES (2, 1, 6, TO_DATE('2023-05-20','YYYY-MM-DD'), TO_DATE('2024-05-20','YYYY-MM-DD'), 35000, '만기', '이영업');

INSERT INTO CONTRACTS (CONTRACT_ID, CUSTOMER_ID, PRODUCT_ID, CONTRACT_DATE, EXPIRY_DATE, MONTHLY_PREMIUM, STATUS, AGENT_NAME)
VALUES (3, 2, 2, TO_DATE('2024-02-10','YYYY-MM-DD'), TO_DATE('2034-02-10','YYYY-MM-DD'), 8000, '유지', '박상담');

INSERT INTO CONTRACTS (CONTRACT_ID, CUSTOMER_ID, PRODUCT_ID, CONTRACT_DATE, EXPIRY_DATE, MONTHLY_PREMIUM, STATUS, AGENT_NAME)
VALUES (4, 3, 3, TO_DATE('2022-08-05','YYYY-MM-DD'), NULL, 5000, '해지', '최지원');

INSERT INTO CONTRACTS (CONTRACT_ID, CUSTOMER_ID, PRODUCT_ID, CONTRACT_DATE, EXPIRY_DATE, MONTHLY_PREMIUM, STATUS, AGENT_NAME)
VALUES (5, 3, 11, TO_DATE('2023-11-11','YYYY-MM-DD'), TO_DATE('2043-11-11','YYYY-MM-DD'), 50000, '유지', '김설계');

INSERT INTO CONTRACTS (CONTRACT_ID, CUSTOMER_ID, PRODUCT_ID, CONTRACT_DATE, EXPIRY_DATE, MONTHLY_PREMIUM, STATUS, AGENT_NAME)
VALUES (6, 4, 16, TO_DATE('2023-07-22','YYYY-MM-DD'), NULL, 10000, '유지', '정프로');

INSERT INTO CONTRACTS (CONTRACT_ID, CUSTOMER_ID, PRODUCT_ID, CONTRACT_DATE, EXPIRY_DATE, MONTHLY_PREMIUM, STATUS, AGENT_NAME)
VALUES (7, 5, 21, TO_DATE('2020-10-10','YYYY-MM-DD'), NULL, 100000, '정지', '이영업');

INSERT INTO CONTRACTS (CONTRACT_ID, CUSTOMER_ID, PRODUCT_ID, CONTRACT_DATE, EXPIRY_DATE, MONTHLY_PREMIUM, STATUS, AGENT_NAME)
VALUES (8, 5, 7, TO_DATE('2024-01-05','YYYY-MM-DD'), TO_DATE('2025-01-05','YYYY-MM-DD'), 2000, '유지', '박상담');

INSERT INTO CONTRACTS (CONTRACT_ID, CUSTOMER_ID, PRODUCT_ID, CONTRACT_DATE, EXPIRY_DATE, MONTHLY_PREMIUM, STATUS, AGENT_NAME)
VALUES (9, 6, 12, TO_DATE('2024-03-01','YYYY-MM-DD'), NULL, 30000, '유지', '최지원');

COMMIT;